<h1> <center>Advent of Code </center></h1>
<h3><center> --- Day 4 : Giant Squid --- </center></h3>

Challenge link : [https://adventofcode.com/2021/day/4](https://adventofcode.com/2021/day/4).

In [65]:
import numpy as np

Load number order and boards:

In [153]:
data = open("data.txt")
order = []
boards = []
board = []

for i, line in enumerate(data.readlines()): 
    if(i==0):
        order = np.fromstring(line, dtype=int, sep=',')
    else:
        if line == "\n":
            if(len(board) != 0):
                board = np.array(board)
                board.reshape([5,5])
                boards.append(board)
            board = []
        else:
            board_line = np.fromstring(line, dtype=int, sep=' ')
            board.append(board_line)
        
boards = np.array(boards)


print("Order :",order)
print("Order count :", order.size)
boards_count = boards.size//25
print("Boards count :", boards_count)

# print(boards)



Order : [73 42 95 35 13 40 99 92 33 30 83  1 36 93 59 90 55 25 77 44 37 62 41 47
 80 23 51 61 21 20 76  8 71 34 58  5 52 22 39 57 17  2 26  0 10 72 19  3
 64 65 82 46 31 63 91 24 18 12  9 79 50 98 69  4 78 54 43 68 87  7 67 48
 28 89 94 53 85 81 49 88  6 96 29 56 97 66 38 16 32 70 74 27 84 86 45 75
 60 15 14 11]
Order count : 100
Boards count : 99


Define check function for one board

In [154]:
def check_board(board):
    result = np.all((board == 1), axis=1)
    result2 = np.all((board == 1), axis=0)
    for i in range(len(result)):
        if result[i] or result2[i]:
            return True
    return False


def check_number_in_board(number,board,board_rep):
    for i,line in enumerate(board):
        for j,col in enumerate(line):
            if(board[i][j] == number):
                board_rep[i][j] = 1
    return board_rep

def score(board, board_check):
    sum = 0
    for i,line in enumerate(board):
        for j,col in enumerate(line):
            if(board_check[i][j] == 0):
               sum+=board[i][j]
    return sum

In [157]:
boards_check = []
for board in boards :
    board_check = np.zeros([5,5])
    boards_check.append(board_check)

boards_check = np.array(boards_check)

# print("Checking :",boards_check)


for iteration,num in enumerate(order):
    for i,board in enumerate(boards):
        boards_check[i] = check_number_in_board(num,board,boards_check[i])
        if(check_board(boards_check[i])):
            print("board", i, "wins after",iteration,"iterations thanks to this number :",num)
            print(boards_check[i])
            print("Score :",score(boards[i],boards_check[i]))
            print("Solution :",score(boards[i],boards_check[i])*num)
            break
    else:
        # Continue if the inner loop wasn't broken.
        continue
    # Inner loop was broken, break the outer.
    break


board 84 wins after 32 iterations thanks to this number : 71
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0.]]
Score : 562
Solution : 39902


In [185]:
boards_check = []
for board in boards :
    board_check = np.zeros([5,5])
    boards_check.append(board_check)

boards_check = np.array(boards_check)

# print("Checking :",boards_check)

winners = []
loser = -1

for iteration,num in enumerate(order):
    for i,board in enumerate(boards):
        boards_check[i] = check_number_in_board(num,board,boards_check[i])
        if(check_board(boards_check[i])):
            if(i not in winners):
                winners.append(i)
            if(len(winners) == boards_count - 1 and loser<0):
                winners.sort()
                for index,winner in enumerate(winners):
                    if(index != winner):
                        print("board",index,'sure lose')
                        loser = index
                        break
            if(len(winners) == boards_count):
                print("Score :",score(boards[index],boards_check[index]))
                print("Solution :",score(boards[index],boards_check[index])*num)
                break
    else:
        # Continue if the inner loop wasn't broken.
        continue
    # Inner loop was broken, break the outer.
    break



board 45 sure lose
Score : 481
Solution : 26936
